### ISSUE TITLE
export function not returning dialogues

### ISSUE THREAD

**Issue by ltsdw** [GitBib/pyasstosrt#3]
Hi there, thanks for your great project

### Describe the problem

So, I used to use a somewhat old version from [pyasstosrt](https://github.com/ltsdw/Asts/blob/main/pylib/pyasstosrt/pyasstosrt/pyasstosrt.py) (it's still works normally).

But recently I thought about changing some stuff, this includes using a newer version of your lib, but with every .ass file I tried so far it only returns None.

### Steps to reproduce

pip install pyasstosrt

```
#my_script.py

from pathlib import Path

from pyasstosrt import Subtitle

path = Path('path-to-my-file-here-ja.ass')
sub = Subtitle(path)

print(sub.export()) #normally it should return a list of objects here and that would be printed, but it returns None
```

### System configuration

* Python version: 3.9

**Comment by ltsdw** [comment]
Thank you :) !

Closing.

**Comment by nedz25** [comment]
Sorry for highjacking this topic..
Is there a way to make it convert a whole folder of Subtitles? that would be great..
thanks for your work.
I use with Termux on Android btw.

**Comment by GitBib** [comment]
@nedz25 If it is possible to run python code, that is:
```
files = glob.glob("*.ass")
for file in files:
    srt_str = Subtitle(file)
    srt_str.export()
```

**Comment by nedz25** [comment]
I have python installed, but unfortunately have no idea how to run codes.

**Comment by GitBib** [comment]
@nedz25 study this manual https://opensource.com/article/20/8/python-android-mobile
